name: Deploy SocialHub Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      env:
        CI: false # Prevents the build from failing on warnings
      
    - name: Deploy to DigitalOcean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USER }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        source: "build/"
        target: "/var/www/socialhub-frontend"
        strip_components: 1
        
    - name: Configure server and restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USER }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          # Ensure proper permissions
          sudo chown -R $USER:$USER /var/www/socialhub-frontend
          sudo chmod -R 755 /var/www/socialhub-frontend
          
          # Restart Nginx to apply changes
          sudo systemctl restart nginx